### ISSUE TITLE
Alignment Automatically Changing to Justified

### ISSUE THREAD

**Issue by whaleyland** [davidrthorn/footnote-stylist#2]
A strange glitch seems to be occurring now with this tool. Regardless of the alignment of the text in the footnotes when "Use as default" or "Update footnote style to match" is used, "Refresh footnotes" is changing all my footnotes to "Justified" alignment. I usually "Align left" my fonts. Any way this little glitch can be fixed? Thanks!

**Comment by davidrthorn** [comment]
Hi Whaleyland

This issue should be fixed now.

cheers
