### ISSUE TITLE
Feature request: Keep a footnote's lines together

### ISSUE THREAD

**Issue by ghost** [davidrthorn/footnote-stylist#3]
Hi,

Often, my footnotes are long and break across pages. Is there a way to elect to stop this happening?

**Comment by davidrthorn** [comment]
Almost certainly not unfortunately. Google docs' layout of pages is not
something add ons have much of any control over. You could try formatting
your footnotes as a single long paragraph and use soft line breaks to
separate the text so it looks like paragraphs. No idea if it'll work...

**Comment by ghost** [comment]
Rats. Thanks for looking into that though - I'll 'let my publisher handle it' :P
